feat: endpoint challenge
hawks-atlanta/proxy-python pull request #33
Opened 2023-10-06 15:13 UTC by MiguelMRojas

- Creating endpoint challenge
- Guided by [https://github.com/hawks-atlanta/gateway-java/pull/56](url)
- Test endpoint

Closes #21

2023-10-06 15:54 UTC, PedroChaparro requested changes
Also, remember that the branch name should start with a semantic type like `feat/`, `fix/`, etc.

2023-10-06 15:54 UTC, PedroChaparro commented on src/controllers/_authentication_controllers.py
> +        decoded_token = jwt.decode(token, options={"verify_signature": False})
The authentication service should be the unique responsible for validating tokens.

2023-10-06 15:54 UTC, PedroChaparro commented on src/controllers/_authentication_controllers.py
> +            jwt = result.auth.token  # noqa: F811
Seems that the comment isn't needed, anyways, avoid using comments to ignore linter warnings instead of fixing them.

2023-10-06 17:07 UTC, MiguelMRojas commented
> Also, remember that the branch name should start with a semantic type like `feat/`, `fix/`, etc.

OMG!, You're absolutely right, I overlooked it, it won't happen again

2023-10-06 17:40 UTC, PedroChaparro requested changes
Tests are missing

2023-10-08 16:23 UTC, PedroChaparro requested changes
You should add another test to, at least, check if an existing token is valid. The following lines are not being tested according to the coverage report: 

![image](https://github.com/hawks-atlanta/proxy-python/assets/62714297/4e64048d-5209-4390-abf8-4b50592a0900)

2023-10-08 23:24 UTC, PedroChaparro approved these changes
Squash and merge :shipit:. 

You can start using this in the React client, but keep in mind that we will need to create another pull request to follow the [.net proxy](https://github.com/hawks-atlanta/proxy-net) specification.

2023-10-08 23:28 UTC, merged