feat: update docs openapi
hawks-atlanta/proxy-python pull request #41
Opened 2023-10-10 02:46 UTC by MiguelMRojas

- Update OpenApi

2023-10-10 13:49 UTC, PedroChaparro requested changes
Please, add the following to the endpoints that require authentication: 

```yaml
security:
        - bearer: []
```

2023-10-10 15:20 UTC, MiguelMRojas commented
> Please, add the following to the endpoints that require authentication:
> 
> ```yaml
> security:
>         - bearer: []
> ```

Done :)

2023-10-10 21:55 UTC, PedroChaparro requested changes
1. There are some duplicated endpoints, Eg. POST `/file/upload` and POST `/files`. 
2. The Bearer token should only be added to the endpoints that require authentication. For instance, the `/auth/login` and `/account/register` do not require authentication, while the `/files/download` does.
3. There are some endpoints with incorrect tags. For instance, the `account/register` endpoint should have the `account` tag.

2023-10-10 22:26 UTC, MiguelMRojas commented
> 1. There are some duplicated endpoints, Eg. POST `/file/upload` and POST `/files`.
> 2. The Bearer token should only be added to the endpoints that require authentication. For instance, the `/auth/login` and `/account/register` do not require authentication, while the `/files/download` does.
> 3. There are some endpoints with incorrect tags. For instance, the `account/register` endpoint should have the `account` tag.

Done, thanks for comment 💯

2023-10-10 22:56 UTC, PedroChaparro requested changes

2023-10-10 22:56 UTC, PedroChaparro commented on docs/spec.openapi.yaml
> +        - account
Should be uppercase: `Account`

2023-10-10 22:56 UTC, PedroChaparro commented on docs/spec.openapi.yaml
>          - Authorization
Should be `Authentication`

2023-10-10 22:56 UTC, PedroChaparro commented on docs/spec.openapi.yaml
> +        - File
Should be `Files`

2023-10-12 00:45 UTC, PedroChaparro approved these changes
Note that this spec is not fully compatible with the `.net` one; however, I think all the methods exposed by the gateway are covered by this spec. Let's see what happens.

Squash and merge.

2023-10-12 01:39 UTC, merged